services:
    training.calculator:
        class: App\Training\Service\Calculator

    training.maths_service:
        class: App\Training\Service\MathService
        arguments:
            - "@training.calculator"